### ISSUE TITLE
it stucks on decryption and repacking:

### ISSUE THREAD

**Issue by matanmi12** [gkpln3/evrit-to-kindle#4]
This is what I get:
```
Script loaded successfully 
Inside java perform function
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/frida/core.py", line 458, in _on_message
    callback(message, data)
  File "/home/oem/Desktop/platform-tools/loader.py", line 24, in handle_message
    filename: str = message['payload']['name'][0]
KeyError: 'payload'
Got all files for com_yit_evritP18615V2, repacking...
Done
```

**Comment by gkpln3** [comment]
There is a new method, you can try it out.
